spring.application.name=recipemanager

spring.datasource.url=jdbc:postgresql://localhost:5432/recipe-manager
spring.datasource.driverClassName=org.postgresql.Driver

spring.datasource.username=recipe_manager_user
spring.datasource.password=recipe_manager_database_password_123

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto = create

recipemanager.app.secret = "adslkdla21312312hdhasjhdhja"
recipemanager.app.expiratonMs = 120000
logging.level.org.springframework.security=DEBUG

//jpa.hibernate.ddl-auto= 'create-drop'
jpa.hibernate.show-sql= true
